version: '3.7'
networks:
  traefik-network:
services:
  traefik:
   image: traefik:latest
   command:
    - "--providers.docker=true"
    - "--entrypoints.traefik.address=:8081"
    - "--entrypoints.minio-api.address=:7878"
    - "--api=true"
    - "--api.insecure=true"
    - "--providers.docker"
   ports:
    - "8081:8081" # Traefik dashboard
    - "7878:7878"
   volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
   networks:
    - traefik-network
 # Minio services
  minio1:
   image: minio/minio:latest
   command: server --console-address ":9001" http://minio{1...4}/data
   ports:
    - "9001:9001"
   volumes:
    - ./data/minio/data1:/data
   networks:
    - traefik-network
   labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.rule=Host(`localhost`)"
    - "traefik.http.routers.minio.entrypoints=minio-api"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.services.minio.loadbalancer.server.scheme=http"
    - "traefik.http.services.minio.loadbalancer.passhostheader=true"
  minio2:
   image: minio/minio:latest
   command: server --console-address ":9001" http://minio{1...4}/data
   ports:
    - "9002:9001"
   volumes:
    - ./data/minio/data2:/data
   networks:
    - traefik-network
   labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.rule=Host(`localhost`)"
    - "traefik.http.routers.minio.entrypoints=minio-api"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.services.minio.loadbalancer.server.scheme=http"
    - "traefik.http.services.minio.loadbalancer.passhostheader=true"
  minio3:
   image: minio/minio:latest
   command: server --console-address ":9001" http://minio{1...4}/data
   ports:
    - "9003:9001"
   volumes:
    - ./data/minio/data3:/data
   networks:
    - traefik-network
   labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.rule=Host(`localhost`)"
    - "traefik.http.routers.minio.entrypoints=minio-api"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.services.minio.loadbalancer.server.scheme=http"
    - "traefik.http.services.minio.loadbalancer.passhostheader=true"
  minio4:
   image: minio/minio:latest
   command: server --console-address ":9001" http://minio{1...4}/data
   ports:
    - "9004:9001"
   volumes:
    - ./data/minio/data4:/data
   networks:
    - traefik-network
   labels:
    - "traefik.enable=true"
    - "traefik.http.routers.minio.rule=Host(`localhost`)"
    - "traefik.http.routers.minio.entrypoints=minio-api"
    - "traefik.http.services.minio.loadbalancer.server.port=9000"
    - "traefik.http.services.minio.loadbalancer.server.scheme=http"
    - "traefik.http.services.minio.loadbalancer.passhostheader=true"

    